### ISSUE TITLE
UI: When hitting cancel on save dialogue, deletes recorded frames

### ISSUE THREAD

**Issue by sayboltm** [michaelmob/WebMCam#69]
Say you realized you didn't click the right frames and want to go back to the 'frame selection' dialogue, so you hit cancel on the 'save file as' dialogue. It goes back to the regular startup screen, seemingly deleting the frames that were just recorded. Any ideas?

Capture audio was checked, though I didn't test it checked/unchecked. Just mentioning because GH mentioned it in related post.

**Comment by paronos** [comment]
You can recover the recorded frames from the [**Win TMP folder**](https://en.wikipedia.org/wiki/Environment_variable#%TMP%) [[#71](https://github.com/tarkusdev/WebMCam/issues/71#issue-624304007)]

**Comment by sayboltm** [comment]
Thank you. Would be nice to have a pointer to this, maybe not a full dialogue recovery option.. I'm not volunteering so I guess I'll close it, unless someone else wants this feature.
